package com.parser

import com.lagradost.cloudstream3.app
import com.lagradost.cloudstream3.utils.AppUtils.parseJson

/**
 * Health verdicts for playlist URLs, generated by CI rather than on-device.
 *
 * The probe ladder that produces this file (`check_m3u.py`) fetches manifests
 * and pulls segment bytes — far too expensive to run on a phone at page load.
 * Hundreds of channels would delay the first paint by tens of seconds, burn
 * battery, and get the user's IP rate-limited by the CDNs hosting the streams.
 *
 * So the work happens in a scheduled workflow and the plugin consumes the
 * result. Only non-alive URLs are listed, which keeps the file a few KB.
 *
 * Keyed by stream URL rather than `tvg-id`, because `tvg-id` is frequently
 * absent in real playlists.
 */
data class StreamStatus(
    val generated: String = "",
    val playlist: String = "",
    val dead: Set<String> = emptySet(),
    val suspect: Set<String> = emptySet(),
) {
    companion object {
        /** Used whenever the status file cannot be read. Treats everything as alive. */
        val EMPTY = StreamStatus()
    }
}

/**
 * Fetches and caches [StreamStatus].
 *
 * **Fails open by design.** If the status file is missing, malformed, or
 * unreachable, every channel is treated as alive. A network failure while
 * fetching a health file must never hide working channels — the same asymmetry
 * that governs the on-device probe, applied one level up.
 *
 * Cached for the process lifetime. The file is regenerated weekly, so there is
 * nothing to gain from refetching within a session.
 */
object StatusIndex {

    private var cached: StreamStatus? = null

    suspend fun get(): StreamStatus {
        cached?.let { return it }

        val status = try {
            val response = app.get(Config.STATUS_URL, timeout = STATUS_TIMEOUT_SECONDS)

            if (response.isSuccessful) {
                parseJson<StreamStatus>(response.text)
            } else {
                StreamStatus.EMPTY
            }
        } catch (e: Exception) {
            // Unreachable, malformed, or schema drift. Fail open.
            StreamStatus.EMPTY
        }

        cached = status
        return status
    }

    /** Test/debug hook: forces the next [get] to refetch. */
    fun invalidate() {
        cached = null
    }

    private const val STATUS_TIMEOUT_SECONDS = 10L
}